### PR TITLE
Handle DA errors, progress towards allowing retry

### LINKED ISSUE #14: Recover from a crash when jobs don't make it to succinct
[When the service starts up](https://github.com/celestiaorg/eq-service/blob/main/service/src/main.rs#L350), it sends all the queued jobs with `JobStatus::Pending` to the worker. We need it to do so for `JobStatus::Waiting` as well, so it catches all the ones that were stuck on Celestia and hadn't yet made it to Succinct.

### PR DESCRIPTION
**Pull request by nuke-web3**
Moves to a recursive / self-feeding worker as a state machine to:
- better spread load over thread & between different jobs
- allow for more clear hooks into the job pipeline at any state in the processing of a job end-to-end

Adds some doc comments and a `just doc` command to create (and open them on linux)

Fixes #14

### CODE REVIEW

File: service/src/main.rs [hunk 1]
```diff
@@ -162,157 +184,189 @@ impl Inclusion for Arc<InclusionService> {
...
                 "job worker received job for commitment: {}",
                 hex::encode(job.commitment.clone())
             );
-            let client = Arc::clone(&self.client);
-            tokio::spawn(prove(
-                job,
-                client,
-                self.queue_db.clone(),
-                self.proof_db.clone(),
-            ));
```
Comment (nuke-web3) [inline service/src/main.rs:178]: Unclear if we need to spawn what replaces this :thinking:

File: service/src/main.rs [hunk 2]
```diff
@@ -162,157 +184,189 @@ impl Inclusion for Arc<InclusionService> {
...
+                ClientError::Call(error_object) => {
+                    // TODO: make this handle errors much better!  See ErrorCode::ServerError(1){
+                    if error_object.message() == "header: not found" {
+                        todo!();
+                    };
+                }
+                // TODO: handle other Celestia JSON RPC errors
+                _ => (),
+            }
+        })
```
Comment (nuke-web3) [inline service/src/main.rs:306]: WIP hook to handle specific JSON RPC errors and decide if the are recoverable/retryable or not

File: service/src/main.rs (hunk 1 above)
Comment (S1nus) [reply service/src/main.rs:178]: it doesn't replace job_worker, which [runs in perpetuity](https://github.com/celestiaorg/eq-service/blob/main/service/src/main.rs#L350). We use `task::spawn` here so it can immediately start waiting for the next job obtained from a user via the [job_receiver](https://github.com/celestiaorg/eq-service/blob/main/service/src/main.rs#L167)

**Review by nuke-web3 — COMMENTED** [review]
Ready for a review, if :+1: we should squash merge & make some followups to tackle from comments. (or keep working)

File: service/src/main.rs (hunk 2 above)
Comment (nuke-web3) [reply service/src/main.rs]: got a better but still very messy thing to replace this in place in https://github.com/celestiaorg/eq-service/pull/20/commits/117c732307979c570736fd922d72d89d00bc7377

File: service/src/main.rs [hunk 3]
```diff
@@ -90,18 +141,31 @@ impl Inclusion for InclusionServiceArc {
...
-                _ => return Err(Status::internal("Invalid state in proof_tree")),
+                JobStatus::Failed(error, retry_status) => {
+                    // TODO: retry or not?
+                    return Ok(Response::new(GetKeccakInclusionResponse {
+                        status: ResponseStatus::Waiting as i32,
+                        response_value: Some(ResponseValue::StatusMessage(format!(
+                            "Retryring: {retry_status:?} ||| Previous Error: {error:?}"
+                        ))),
+                    }));
+                }
```
Comment (nuke-web3) [inline service/src/main.rs:158]: Unclear if we want to retry when a user hits the RPC (repeatedly), or have some dedicated call to request an retry

I would vote we do add a retryable job back to the queue each time the RPC gets a call for a previously failed job.
```suggestion
                JobStatus::Failed(error, retry_status) => {
                    // send a job back to the worker
                    return Ok(Response::new(GetKeccakInclusionResponse {
                        status: ResponseStatus::Waiting as i32,
                        response_value: Some(ResponseValue::StatusMessage(format!(
                            "Retryring: {retry_status:?} ||| Previous Error: {error:?}"
                        ))),
                    }));
                }
```

File: service/src/main.rs [hunk 4]
```diff
@@ -154,166 +231,237 @@ impl Inclusion for InclusionServiceArc {
...
+                    let e = InclusionServiceError::CelestiaError(
+                        "Unhandled Celestia SDK error".to_string(),
+                    );
+                    error!("{job:?} failed, not recoverable: {e}");
+                    let job_status = JobStatus::Failed(e, None);
+                    return self.finalize_job(&job_key, job_status);
+                }
+            }
+        };
+        let blob = try_blob.expect("exhaustive error handling");
```
Comment (nuke-web3) [inline service/src/main.rs:353]: I really don't  like how verbose this is. For sure want to followup with something more clean & flexible.

**Review by S1nus — APPROVED** [review]
tested in staging, looks good.

**Comment by nuke-web3** [comment]
Made a few more refactors and didn't see you made those changes before, I came to the same conclusion, but went a bit further to refactor into a bit more fine grained feature gating in `common` . Take one last look?

Also not sure if we should merge, or at least not run in staging, until I track down a new issue blocking on https://github.com/celestiaorg/eq-service/blob/9b513f6e117b0d023d5e3eae167de86e0c9c4f36/service/src/main.rs#L404-L406

will report back here in an issue, or push up a fix.

**Comment by nuke-web3** [comment]
See #29 for next steps to fix the blocking issue, PR incoming shortly. Merging this one.
